import os
import json

GAME_TITLE = "CORP HEIST"
VERSION = "1.0.0"
SAVE_FILE = "save_data.json"

WIDTH, HEIGHT = 1280, 720
FPS = 60

COLORS = {
    "bg_dark": (10, 10, 18),
    "bg_panel": (18, 18, 30),
    "bg_card": (25, 25, 42),
    "bg_card_hover": (35, 35, 55),
    "bg_header": (15, 15, 25),
    "neon_blue": (0, 170, 255),
    "neon_cyan": (0, 230, 230),
    "neon_gold": (255, 200, 0),
    "neon_pink": (255, 0, 128),
    "neon_green": (0, 255, 140),
    "neon_red": (255, 50, 50),
    "neon_purple": (170, 0, 255),
    "text_white": (240, 240, 250),
    "text_dim": (140, 140, 170),
    "text_gold": (255, 215, 0),
    "text_danger": (255, 80, 80),
    "text_success": (80, 255, 140),
    "border_dim": (50, 50, 80),
    "border_active": (0, 170, 255),
    "white": (255, 255, 255),
    "black": (0, 0, 0),
    "hp_bar": (255, 60, 60),
    "hp_bg": (60, 20, 20),
    "xp_bar": (0, 200, 255),
    "xp_bg": (20, 40, 60),
    "shield_bar": (0, 200, 120),
    "shield_bg": (15, 50, 35),
}

CORPORATIONS = {
    "NEXUS_FINANCIAL": {
        "name": "Nexus Financial",
        "color": (0, 170, 255),
        "description": "Корпорация алгоритмического трейдинга",
        "bonus_type": "crit",
        "bonus_value": 0.15,
    },
    "VERTEX_CONSULTING": {
        "name": "Vertex Consulting",
        "color": (255, 200, 0),
        "description": "Консалтинговый гигант M&A сделок",
        "bonus_type": "gold",
        "bonus_value": 0.20,
    },
    "APEX_PHARMA": {
        "name": "Apex Biotech",
        "color": (0, 255, 140),
        "description": "Научно-исследовательский холдинг",
        "bonus_type": "xp",
        "bonus_value": 0.25,
    },
    "OBSIDIAN_TECH": {
        "name": "Obsidian Tech",
        "color": (170, 0, 255),
        "description": "Кибербезопасность и данные",
        "bonus_type": "dodge",
        "bonus_value": 0.10,
    },
    "CRIMSON_HOLDINGS": {
        "name": "Crimson Holdings",
        "color": (255, 50, 50),
        "description": "Инвестиционный фонд закрытого типа",
        "bonus_type": "damage",
        "bonus_value": 0.12,
    },
}

HERO_TEMPLATES = {
    "analyst": {
        "name": "Аналитик",
        "role": "Финансовый аналитик",
        "hp": 80,
        "attack": 12,
        "defense": 8,
        "speed": 14,
        "crit_rate": 0.15,
        "crit_dmg": 1.5,
        "dodge": 0.05,
        "abilities": ["Квантовый анализ", "Арбитражный удар", "Стресс-тест"],
        "description": "Видит паттерны рынка. Каждый удар точнее предыдущего.",
        "tier": "B",
    },
    "consultant": {
        "name": "Консультант",
        "role": "Стратегический консультант",
        "hp": 100,
        "attack": 15,
        "defense": 10,
        "speed": 10,
        "crit_rate": 0.10,
        "crit_dmg": 1.8,
        "dodge": 0.08,
        "abilities": ["Due Diligence", "Синергия", "Выкуп акций"],
        "description": "Ломает бизнес-планы противников. Харизма = оружие.",
        "tier": "A",
    },
    "quant": {
        "name": "Квант",
        "role": "Квантовый программист",
        "hp": 70,
        "attack": 18,
        "defense": 5,
        "speed": 16,
        "crit_rate": 0.20,
        "crit_dmg": 2.0,
        "dodge": 0.12,
        "abilities": ["Нейросеть", "HFT-шторм", "Алгоритм хаоса"],
        "description": "Вычисляет идеальную атаку за наносекунды.",
        "tier": "S",
    },
    "lawyer": {
        "name": "Юрисконсульт",
        "role": "Корпоративный юрист",
        "hp": 110,
        "attack": 10,
        "defense": 15,
        "speed": 8,
        "crit_rate": 0.08,
        "crit_dmg": 1.3,
        "dodge": 0.03,
        "abilities": ["Антимонопольный щит", "Иск о банкротстве", "NDA"],
        "description": "Неуязвим к юридическим атакам. Щит из законов.",
        "tier": "A",
    },
    "ceo": {
        "name": "CEO",
        "role": "Главный исполнительный директор",
        "hp": 130,
        "attack": 20,
        "defense": 12,
        "speed": 12,
        "crit_rate": 0.18,
        "crit_dmg": 2.2,
        "dodge": 0.07,
        "abilities": ["Волюнтаризм", "Реструктуризация", "Golden Parachute"],
        "description": "Командует. Его слово — закон. Его удар — приговор.",
        "tier": "SSR",
    },
    "data_scientist": {
        "name": "Data Scientist",
        "role": "Специалист по данным",
        "hp": 85,
        "attack": 16,
        "defense": 7,
        "speed": 13,
        "crit_rate": 0.22,
        "crit_dmg": 1.7,
        "dodge": 0.15,
        "abilities": ["Deep Learning", "Предиктивный удар", "Data Mining"],
        "description": "Находит слабые места. Каждый следующий удар сильнее.",
        "tier": "S",
    },
    "risk_manager": {
        "name": "Risk Manager",
        "role": "Управление рисками",
        "hp": 120,
        "attack": 11,
        "defense": 18,
        "speed": 9,
        "crit_rate": 0.06,
        "crit_dmg": 1.4,
        "dodge": 0.20,
        "abilities": ["Хеджирование", "Стресс-тест", "Кризис-менеджмент"],
        "description": "Непробиваемый. Минимизирует каждый входящий урон.",
        "tier": "A",
    },
    "trader": {
        "name": "Трейдер",
        "role": "Высокочастотный трейдер",
        "hp": 75,
        "attack": 22,
        "defense": 4,
        "speed": 20,
        "crit_rate": 0.25,
        "crit_dmg": 2.5,
        "dodge": 0.18,
        "abilities": ["Flash Crash", "Margin Call", "Short Squeeze"],
        "description": "Быстрее света. Криты каждый второй удар.",
        "tier": "SSR",
    },
    "compliance": {
        "name": "Compliance Officer",
        "role": "Офицер по комплаенсу",
        "hp": 105,
        "attack": 13,
        "defense": 14,
        "speed": 11,
        "crit_rate": 0.12,
        "crit_dmg": 1.6,
        "dodge": 0.10,
        "abilities": ["KYC-сканирование", "AML-удар", "Санкционный блок"],
        "description": "Знает каждого. Никто не скроется от его проверок.",
        "tier": "A",
    },
    "brand_director": {
        "name": "Brand Director",
        "role": "Директор по бренду",
        "hp": 90,
        "attack": 14,
        "defense": 9,
        "speed": 15,
        "crit_rate": 0.16,
        "crit_dmg": 1.9,
        "dodge": 0.14,
        "abilities": ["PR-удар", "Кризис-коммуникация", "Rebranding"],
        "description": "Управляет восприятием. Враги теряют-confidence.",
        "tier": "S",
    },
}

ENEMY_TEMPLATES = {
    "intern": {
        "name": "Стажёр",
        "hp": 40,
        "attack": 5,
        "defense": 3,
        "speed": 6,
        "xp_reward": 15,
        "gold_reward": 10,
    },
    "junior_analyst": {
        "name": "Младший аналитик",
        "hp": 60,
        "attack": 8,
        "defense": 5,
        "speed": 8,
        "xp_reward": 30,
        "gold_reward": 25,
    },
    "mid_manager": {
        "name": "Менеджер среднего звена",
        "hp": 90,
        "attack": 12,
        "defense": 10,
        "speed": 9,
        "xp_reward": 55,
        "gold_reward": 45,
    },
    "vp": {
        "name": "Вице-президент",
        "hp": 140,
        "attack": 18,
        "defense": 14,
        "speed": 11,
        "xp_reward": 90,
        "gold_reward": 75,
    },
    "competitor_boss": {
        "name": "Босс-конкурент",
        "hp": 200,
        "attack": 25,
        "defense": 18,
        "speed": 13,
        "xp_reward": 160,
        "gold_reward": 130,
    },
    "regulator": {
        "name": "Регулятор",
        "hp": 250,
        "attack": 30,
        "defense": 22,
        "speed": 10,
        "xp_reward": 220,
        "gold_reward": 180,
    },
    "activist_investor": {
        "name": "Активист-инвестор",
        "hp": 300,
        "attack": 35,
        "defense": 25,
        "speed": 14,
        "xp_reward": 300,
        "gold_reward": 250,
    },
    "hostile_corp": {
        "name": "Вражеская корпорация",
        "hp": 500,
        "attack": 45,
        "defense": 30,
        "speed": 12,
        "xp_reward": 500,
        "gold_reward": 400,
    },
}

FLOOR_CONFIGS = [
    {
        "name": "Стажировка",
        "floor": 1,
        "floors_total": 10,
        "building": "Бизнес-центр 'Старт'",
        "enemies": ["intern"],
        "boss": "junior_analyst",
        "unlock_level": 1,
        "color": (100, 100, 120),
    },
    {
        "name": "Офис-планировка",
        "floor": 2,
        "floors_total": 10,
        "building": "Башня 'Горизонт'",
        "enemies": ["intern", "junior_analyst"],
        "boss": "mid_manager",
        "unlock_level": 5,
        "color": (0, 170, 255),
    },
    {
        "name": "Конференц-зал",
        "floor": 3,
        "floors_total": 10,
        "building": "Небоскрёб 'Вершина'",
        "enemies": ["junior_analyst", "mid_manager"],
        "boss": "vp",
        "unlock_level": 10,
        "color": (255, 200, 0),
    },
    {
        "name": "Кабинет директора",
        "floor": 4,
        "floors_total": 10,
        "building": "Небоскрёб 'Нексус'",
        "enemies": ["mid_manager", "vp"],
        "boss": "competitor_boss",
        "unlock_level": 20,
        "color": (0, 255, 140),
    },
    {
        "name": "Рубикон",
        "floor": 5,
        "floors_total": 10,
        "building": "Штаб-квартира 'Obsidian'",
        "enemies": ["vp", "competitor_boss"],
        "boss": "regulator",
        "unlock_level": 35,
        "color": (170, 0, 255),
    },
    {
        "name": "Корпоративный пентхаус",
        "floor": 6,
        "floors_total": 10,
        "building": "Башня 'Crimson Tower'",
        "enemies": ["competitor_boss", "regulator"],
        "boss": "activist_investor",
        "unlock_level": 50,
        "color": (255, 50, 50),
    },
    {
        "name": "Тронный зал",
        "floor": 7,
        "floors_total": 5,
        "building": "Глобальная штаб-квартира",
        "enemies": ["regulator", "activist_investor"],
        "boss": "hostile_corp",
        "unlock_level": 75,
        "color": (255, 215, 0),
    },
]

PASSIVE_NODES = {
    "market_momentum": {
        "name": "Рыночный моментум",
        "description": "+5% ATK за каждый уровень",
        "max_level": 20,
        "cost_base": 50,
        "cost_mult": 1.5,
        "stat": "attack",
        "flat": 2,
    },
    "risk_tolerance": {
        "name": "Толерантность к рискам",
        "description": "+3% CRIT RATE за уровень",
        "max_level": 15,
        "cost_base": 80,
        "cost_mult": 1.6,
        "stat": "crit_rate",
        "flat": 0.02,
    },
    "financial_cushion": {
        "name": "Финансовая подушка",
        "description": "+8% HP за уровень",
        "max_level": 20,
        "cost_base": 40,
        "cost_mult": 1.4,
        "stat": "hp",
        "flat": 5,
    },
    "data_edge": {
        "name": "Краевое преимущество",
        "description": "+4% DODGE за уровень",
        "max_level": 15,
        "cost_base": 70,
        "cost_mult": 1.55,
        "stat": "dodge",
        "flat": 0.02,
    },
    "compound_growth": {
        "name": "Сложный процент",
        "description": "+6% CRIT DMG за уровень",
        "max_level": 15,
        "cost_base": 90,
        "cost_mult": 1.65,
        "stat": "crit_dmg",
        "flat": 0.05,
    },
    "network_effect": {
        "name": "Эффект сети",
        "description": "+4 SPD за уровень",
        "max_level": 15,
        "cost_base": 60,
        "cost_mult": 1.5,
        "stat": "speed",
        "flat": 2,
    },
    "brand_value": {
        "name": "Бренд-стоимость",
        "description": "+8% золота за уровень",
        "max_level": 10,
        "cost_base": 120,
        "cost_mult": 1.8,
        "stat": "gold_mult",
        "flat": 0.08,
    },
    "research_grant": {
        "name": "Научный грант",
        "description": "+10% XP за уровень",
        "max_level": 10,
        "cost_base": 120,
        "cost_mult": 1.8,
        "stat": "xp_mult",
        "flat": 0.10,
    },
}

PASSIVE_TIER_BONUS = {
    "B": 1.0,
    "A": 1.1,
    "S": 1.25,
    "SSR": 1.5,
}

GACHA_COST = 100
GACHA_MULTICOST = 900
GACHA_RATES = {
    "B": 0.55,
    "A": 0.30,
    "S": 0.12,
    "SSR": 0.03,
}

WARNING_TEXTS = [
    "⚠ ВНИМАНИЕ: Данный продукт содержит элементы рандомизации.",
    "⚠ Все персонажи вымышлены. Совпадения случайны.",
    "⚠ Игра не является финансовой консультацией.",
    "⚠ Игроки младше 18+ не должны использовать донат.",
    "⚠ Играйте ответственно. Расходы могут расти.",
    "⚠ Никакой гарантии прибыли в реальной жизни.",
]
